### ISSUE TITLE
How to add friends for an individual uid?

### ISSUE THREAD

**Issue by narmuni123** [cometchat-pro/flutter-chat-app#4]
Hi, I want to know how can I add friends to a user. @Shantanu-CometChat

**Comment by smit-sk** [comment]
You have to call POST request as shown below.
Ex - 
 var header = {
      'content-type': 'Application/json',
      'apikey': "APIKEY",
    };
    var data = {
      'accepted': ['{UID}']
    };
    http.Response response = await http.post(
        Uri.parse(
            "https://{APPID}.api-{REGION}.cometchat.io/v3/users/{UID}/friends"),
        headers: header,
        body: jsonEncode(data));
